# Site
repository: p17anto2/cv
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Tolias
title: Student
email: p17anto2@ionio.gr

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username: p17anto2
# linkedin_username: jameswgrant
# youtube_username: globalmtb

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: About Me
# about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs

  I am a student at the Department of Informatics of the Ionian University, interested in Data Science, Systems Security and Low-Level Programming.

content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Ionian University
        caption: 2017 - Ongoing
        sub_title: Department Of Informatics
        description: | #
          Still meeting wonderful people and learning new skills and tricks.

  - title: Skills and Interests
    layout: text
    content: | #
      - C
      - Python
      - \*nix Systems
      - Data Science
  - title: And Now For Something Completely Different
    layout: text
    content: | # this will include new lines to allow paragraphs
      As well as (almost) computer scientist, I'm also an (aspiring) musician and a (wannabe) sound engineer.

# Footer
# footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
